import { HELI_TYPES } from './heli-types';

export const G = {
    goalCount: 0,
    totalRescued: 0,
    objectives: [] as any[],
    menuHover: Object.fromEntries(HELI_TYPES.map(h => [h.id, false])),
    menuAngles: Object.fromEntries(HELI_TYPES.map(h => [h.id, -0.5])),
    points: [] as any[],
    particles: [] as any[],
    debris: [] as any[],
    CARRIER: {} as any,
    BOATS: [] as any[],
    seaTime: 0,
    payloads: [] as any[],
    activePayload: null as any,
    rescuerSwing: { x: 0, y: 0, vx: 0, vy: 0 },
    parkedHelis: [
        { type: 'jayhawk', xRel: -2.5, yRel: -7.0, angle: Math.PI * 0.19 },
        { type: 'jayhawk', xRel: -2.7, yRel: -1.5, angle: Math.PI * 0.15 },
        { type: 'dolphin', xRel: 2.5, yRel: -7.0, angle: Math.PI * 0.55 },
    ],
    heli: {
        type: 'dolphin',
        x: 0,
        y: 0,
        z: 0.5,
        vx: 0,
        vy: 0,
        vz: 0,
        angle: 0,
        tilt: 0,
        roll: 0,
        winch: 0,
        fuel: 100,
        engineOn: false,
        rotorRPM: 0,
        rotationPos: 0,
        onboard: 0,
        maxLoad: 5,
        accel: 0.0025,
        friction: 0.99,
        tiltSpeed: 0.02,
        fuelRate: 0.012,
        liftPower: 0.003,
        inAir: false,
        cargoResist: 1.0,
    },
    wind: { x: 0, y: 0, phase: 0, angle: Math.random() * Math.PI * 2, varOffset: 0 } as any,
    keys: {} as Record<string, boolean>,
    flocks: [] as any[],
    TREES_MAP: null as any,
    PAD: null as any,
    START_POS: null as any,
    fuelTruck: { state: 'PARKED', x: 0, y: 0, angle: 0, arm: 0, parkX: 0, parkY: 0, parkAngle: 0, t: 0, wps: null as null, wpI: 0, targetX: null as number | null, targetY: null as number | null },
};

export type GameState = typeof G;
